### PR TITLE
Fixes #249

### LINKED ISSUE #249: Refarctoring bugs
Some bugs where introduced while refactoring.

### PR DESCRIPTION
**Pull request by 1-alex98**

### CODE REVIEW

**Review by bukajsytlos — DISMISSED** [review]

**Review by Brutus5000 — DISMISSED** [review]
Instead of the two checks on `getRevealWinner` compare with `votingSubject.getRevealWinner() == Boolean.FALSE`

To be honest I have no clue what this is validating. What is a VotingSubjectRevealWinnerValidator actually validating? Your code is changing it's behavior, but it is untested and undocumented. I demand unit tests to verify the desired behavior.

**Comment by axel1200** [comment]
I got 2 integration tests on this but bukajsytlos changed the logic in a way that was similar but not the same

**Comment by bukajsytlos** [comment]
But Brutus is right. I changed/broke the logic but tests still passed. So there is something missing on test side, right?

**Comment by axel1200** [comment]
Well yes I did not test all cases, I tested the security relevant ones

**Comment by axel1200** [comment]
I will add another test

**Comment by axel1200** [comment]
Btw if you merge this could you deploy it as well?

**Comment by Brutus5000** [comment]
Probably not. Depends on required database migrations.

**Comment by axel1200** [comment]
oh ok. hmm

**Review by Brutus5000 — APPROVED** [review]

**Comment by axel1200** [comment]
👍 only needs to be deployed some when then ftx can do his ladder vote

**Comment by Brutus5000** [comment]
@axel1200 it's on prod now

**Comment by axel1200** [comment]
Cool only missing the modor PR and I can tell ftx his ladder voting stuff is done

**Pull request merged**
