### PR TITLE
allow moderators to update steamids

### PR DESCRIPTION
**Pull request by Geosearchef**

### CODE REVIEW

**Review by 1-alex98 — APPROVED** [review]

**Comment by 1-alex98** [comment]
U can now merge it

**Comment by 1-alex98** [comment]
Oh btw do u want them to allow to change it or only to set it to null? If only to Null look at what I used with the hidden attribute on maps. I made the author only able to set it to true but not to false in a similar way you can only allow to set it to null

**Review by Brutus5000 — CHANGES_REQUESTED** [review]
Audit log annotations are missing

**Comment by Brutus5000** [comment]
Does no longer fit into the permission system.

**Pull request closed without merging**
