### PR TITLE
Fixes #382 Filtering by game type does not work

### LINKED ISSUE #382: Filtering by game type does not work
https://api.faforever/data/game?filter=gameType==DEMORALIZATION returns no data

### PR DESCRIPTION
**Pull request by bukajsytlos**

### CODE REVIEW

**Review by Brutus5000 — APPROVED** [review]

**Comment by 1-alex98** [comment]
Why the fuck does this work for validity and not game type???

**Comment by axel1200** [comment]
It seems be have the same issue on other enums:
for example the faction enum 

----
Example request: https://api.faforever.com/data/game/?page[limit]=1&filter=playerStats.faction=="AEON";validity=="VALID";featuredMod.id==6;endTime=gt="2019-12-31T23:00:00Z"&page[totals]

**Comment by 1-alex98** [comment]
It seems we have also the same issue with other enums

**Comment by 1-alex98** [comment]
for example the faction enum in player stats, can we think of a gernal solution?

**Comment by FemtoZetta** [comment]
For example the following request doesn't deliver the expected amount of games. There are way too many games for Aeon, and if you do the same with Cybran it would be the least played faction...

https://api.faforever.com/data/game/?page[limit]=1&filter=playerStats.faction=="AEON";validity=="VALID";featuredMod.id==6;endTime=gt="2019-12-31T23:00:00Z"&page[totals]

The one game it returns (10778720) also doesn't have an Aeon player in it.

**Comment by bukajsytlos** [comment]
I'll try to take a look tomorrow

**Comment by 1-alex98** [comment]
cool thx

**Pull request merged**
