### PR TITLE
Use generic in AbstractEntity to allow proper setter chaining

### PR DESCRIPTION
**Pull request by Sheikah45**

### CODE REVIEW

**Comment by bukajsytlos** [comment]
Will this work? I think we need field level annotations to be able to use custom setters. And I think lombok has something like this. (@Accessors)

**Comment by Sheikah45** [comment]
The chaining is already set in the lombok.config. The issue is just that it returns an AbstractEntity rather than the class it is used on

**Comment by Sheikah45** [comment]
It also works fine when I run it locally as I think elide only looks for the naming conventions when set at the property level

**Review by bukajsytlos — APPROVED** [review]

**Review by Brutus5000 — APPROVED** [review]
I love recursions

**Pull request merged**
