### PR TITLE
addition of min size for display_name column

### PR DESCRIPTION
**Pull request by mijanahmed**

### CODE REVIEW

**Comment by 1-alex98** [comment]
Commits should contain a fix #issue-number

**Review by 1-alex98 — CHANGES_REQUESTED** [review]
Please also change mod display name min length then

**Comment by Brutus5000** [comment]
Hey guys,
just changing the JPA definition of the field does not give any feedback to the user why he cannot upload the map. The check needs to be done in the `MapService` with a new ErrorCode. The whole thing needs unit tests as well.

**Comment by 1-alex98** [comment]
@mijanahmed if you are interested in contirbuting to faf in gernal consider joining our slack, ask any moderator on discord(https://discord.gg/yjuNbH) or IRC chat.

**Comment by Brutus5000** [comment]
Closed due to inactivity

**Pull request closed without merging**
