### PR TITLE
Enable force rename player #257

### PR DESCRIPTION
**Pull request by basalt79**

### CODE REVIEW

**Review by 1-alex98 — DISMISSED** [review]
Nice looks good, if you want you can implement it in the faf-moderator-client as well.

**Comment by 1-alex98** [comment]
Please make commit message as follows 

[short title]
[new line]
[further description(optional)]
Fixes #[issue number]

if you do so github will be able to parse message and also close issue when commit gets merged

**Comment by basalt79** [comment]
> if you do so github will be able to parse message and also close issue when commit gets merged

thx for the hint.

**Comment by 1-alex98** [comment]
Look at what codacy complains about https://app.codacy.com/app/FAForever/faf-java-api/pullRequest?prid=2477271

**Comment by basalt79** [comment]
> Look at what codacy complains about https://app.codacy.com/app/FAForever/faf-java-api/pullRequest?prid=2477271

i fixed the unused variable, but the hardcoded IP was already in before. and also got recognized before https://app.codacy.com/app/FAForever/faf-java-api/file/25063435672/issues/source?bid=4098349&fileBranchId=4098349#l178

**Comment by 1-alex98** [comment]
That's fine Id say

**Review by 1-alex98 — APPROVED** [review]

**Comment by 1-alex98** [comment]
Did you follow the slack invite?

**Comment by basalt79** [comment]
I got no invite so far.

**Comment by 1-alex98** [comment]
Ups I must have messed it up again, lemme check. Maybe It was somebody else I invited then. Send me an Email and I will send you an slack invite.  Or email downlord downlord@faforever.com does not matter. Or is your email govin[...]@gmail because I sent out a slack invite to that one.

**Comment by basalt79** [comment]
> govin

no, thats not me, i contacted downlord

**Review by Brutus5000 — APPROVED** [review]
This is really a high quality PR. Thank you very much.

The only thing I'd like to change in the long run could be the OAuth scope for moderator activity. But for now it should suffice.

**Comment by micheljung** [comment]
Hi @basalt79 and thanks for contributing! I agree with brutus :-) With the small addition that each commit should do what it says; the extractions to constants (which I endorse) have nothing to do with "force rename" and do not "fix #257". Just for the next time :)

Yes, I am a pedant :) But with good intentions.

**Pull request merged**
