### PR TITLE
Provide image urls for division images

### PR DESCRIPTION
**Pull request by BlackYps**
The next version of the league service will provide the urls of the folders containing the division images, so the client doesn't have to store it. This provides flexibility if we ever want to change the url.

### CODE REVIEW

**Review by Brutus5000 — COMMENTED** [review]
I think this needs an update (key -> url)

**Comment by BlackYps** [comment]
coincidentally I'm working on it right now, but I got distracted by a certain ci problem with the league service :D

**Comment by BlackYps** [comment]
So here is my first try on computing the final url for the subdivisions. Some questions:
I noticed that other enrichers pull the basae url from the FafApiProperties. How are they set? Seems to be like basic configuration not stored in the db.
I think it doesn't apply in my case, because the base urls are actually stored in a db table. Do I still need some annotation on the enhance method?
Also do we want to expose the base urls on the league object? It is not really necessary, but may be nice to have.

**Comment by Brutus5000** [comment]
> I noticed that other enrichers pull the basae url from the FafApiProperties. How are they set? Seems to be like basic configuration not stored in the db.

No they are part of the application propertiers classes below FafApiProperties (either application.yaml or read from env variables).

> I think it doesn't apply in my case, because the base urls are actually stored in a db table. Do I still need some annotation on the enhance method?

No in that case you don't need it.

**Comment by BlackYps** [comment]
I talked with Sheikah and we agreed that it is not really desireable to have the base urls exposed on the league endpoint. Is there a way how I can access them for the enricher without having them public?

**Comment by BlackYps** [comment]
@Brutus5000

**Comment by bukajsytlos** [comment]
lgtm, but I don't like the concept of storing base paths in DB, when it is more runtime configuration thing

**Review by bukajsytlos — APPROVED** [review]
lgtm, if concept is ok

**Review by Brutus5000 — APPROVED** [review]

**Pull request merged**
