### PR TITLE
Add terms of service and fix some local profile run config

### PR DESCRIPTION
**Pull request by Sheikah45**

### CODE REVIEW

**Review by Brutus5000 — CHANGES_REQUESTED** [review]
Test emails should be minimal dummies and contain info how to generate html out of mjml

**Review by bukajsytlos — DISMISSED** [review]
lgtm. I second, that test email could be simpler

**Comment by Sheikah45** [comment]
I don't know what info is important to generate html out of mjml @Brutus5000 do you have a small sample you built from?

**Comment by Brutus5000** [comment]
HTML is not important for the test sample, all you want is the app to launch.

It should: 
- contain all variables available for that file
- contain a text like: "To generate proper html code use the template in src/main/mjml with an mjml parser (e.g. use the IntelliJ plugin for MJML or follow the instructions on https://documentation.mjml.io/#usage")

**Comment by Sheikah45** [comment]
Alright I minimized it all

**Review by bukajsytlos — APPROVED** [review]
:+1:

**Review by Brutus5000 — APPROVED** [review]

**Pull request merged**
